version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:13
    container_name: mercury-postgres
    environment:
      POSTGRES_DB: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: mercury_secure_password_2024
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - mercury-network

  # Guacamole Daemon
  guacd:
    image: guacamole/guacd:1.5.0
    container_name: mercury-guacd
    restart: unless-stopped
    networks:
      - mercury-network

  # Apache Guacamole Web Application
  guacamole:
    image: guacamole/guacamole:1.5.0
    container_name: mercury-guacamole
    environment:
      GUACD_HOSTNAME: guacd
      GUACD_PORT: 4822
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: mercury_secure_password_2024
      POSTGRES_HOSTNAME: postgres
    depends_on:
      - postgres
      - guacd
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - mercury-network

volumes:
  postgres_data:

networks:
  mercury-network:
    driver: bridge 