version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:13
    container_name: ${CONTAINER_PREFIX}-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - mercury-network

  # Guacamole Daemon
  guacd:
    image: guacamole/guacd:${GUACD_VERSION}
    container_name: ${CONTAINER_PREFIX}-guacd
    restart: unless-stopped
    networks:
      - mercury-network

  # Apache Guacamole Web Application
  guacamole:
    image: guacamole/guacamole:${GUACAMOLE_VERSION}
    container_name: ${CONTAINER_PREFIX}-guacamole
    environment:
      GUACD_HOSTNAME: guacd
      GUACD_PORT: ${GUACD_PORT}
      POSTGRES_DATABASE: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOSTNAME: postgres
    depends_on:
      - postgres
      - guacd
    restart: unless-stopped
    ports:
      - "0.0.0.0:${GUACAMOLE_PORT}:8080"
    networks:
      - mercury-network

volumes:
  postgres_data:

networks:
  mercury-network:
    driver: bridge 